### ISSUE TITLE
Save assessments in the tool

### ISSUE THREAD

**Issue by coire1** [Project-Catalyst/ca-tool#13]
add a way to save the assessments within the tool
make clear UI to make people understand the the assessment have to be copy pasted to ideascale later.

This is related #12

**Comment by coire1** [comment]
We need:
- [ ] a disclaimer message when creating an assessment
- [ ] a disclaimer message when deleting an assessment

**Comment by fhilipk** [comment]
I confirm that this tool is only to be used for compiling purpose. I understand that the assessments MUST be submitted through IdeaScale AND that this interface in saved locally on the browser, data will be lost if the cache is cleared.
