### ISSUE TITLE
Add guiding questions for assessment criteria

### ISSUE THREAD

**Issue by coire1** [Project-Catalyst/ca-tool#17]
**For each assessment criteria we need to add a list of guiding question to help CAs preparing the assessments.
Please suggest new question referencing the related criteria with the number.
1, 2, 3 are for standard challenges
3, 4, 5 are for Challenge Setting
Questions could also be specific for challenges. If it's the case, please specify also the challenge.**

1. Impact: This proposal effectively addresses the challenge
    - Have you checked if the problem statement defines a problem within the challenge?
    - Have you checked if the proposal has a positive impact on the Cardano ecosystem?
2. Feasibility: Given experience and plan presented it is highly likely this proposal will be implemented successfully
    - Have you checked if the proposer's team has relevant experience and/or references?
    - Have you checked if there is a detailed implementable plan?
    - Have you checked if the budget is understandable and reasonable?
3. Auditability: The information provided is sufficient to audit the progress and the success of the proposal.
    - Have you checked if metrics / KPIs are presented and make sense?
    - Have you checked if the community can track the progress of the proposal?
4. Alignment: This challenge is critical to achieve Cardano's mission.
5. Feasibility: The Catalyst community has the capacity to address the challenge.
6. Verifiability: Success criteria and suggested metrics are set correctly to measure progress in addressing the challenge.

**Discussion moved to: https://docs.google.com/document/d/1nBSl7RS8boPt1b6q6OMMpuchH87nFjN6KlFSEtj7Sxc/edit#**

**Comment by VanCardui** [comment]
Under "feasibility", I would add something like "Have you checked that the proposers have indicated some awareness of the risks to the project and have given some indication of how they will mitigate them?

**Comment by grech1993** [comment]
Under Impact, I woul include:

Do the KPIs indicated in the proposal match the ones indicated in the challenge? If not, how relevant are the indicated KPIs to this particular challenge ?

**Comment by kctdfh** [comment]
Me and some of the other challenge team members for the Nation Building Dapps challenge came up with a self assessment rubric for our proposers to streamline feedbacks. Here's our collaborative Google Sheets with the rubric. We have a ton of guiding questions and descriptions in there for each criteria. They're based off of IOHK's guidelines and comments on Fund 6 proposals by CAs. 

Feel free to use it however you see fit.

https://docs.google.com/spreadsheets/d/1TYGyy-4rqFJaUtlR7f0J40W-IQcZNZbsx9BszpYtvpI/edit

**Comment by ketniptrip** [comment]
I ususally have to change between the challenge brief and the assessment, so some sort of connection between the campaign brief per challenge and the tool might be helpful. Can it pop up as like a hovering information, or is that too big and too difficult for more than 20 challenges?

**Comment by ketniptrip** [comment]
So "the proposal has a positive impact on the Cardano Ecosystem" - you could (but don´t have to) add "Catalyst" to avoid situations where unexperienced or new CAs think, that a proposal is not relevant because it doesn´t support the Cardano blockchain. This is minor and can be disregarded.

**Comment by FilipBl4gojevic** [comment]
I suggest adding the CA guide link (https://cardanocataly.st/en/community-advisor/guide.html) when the Create Assessment button is pushed

**Comment by coire1** [comment]
Discussion moved to: https://docs.google.com/document/d/1nBSl7RS8boPt1b6q6OMMpuchH87nFjN6KlFSEtj7Sxc/edit#
