### ISSUE TITLE
F8 Data update

### ISSUE THREAD

**Issue by coire1** [Project-Catalyst/ca-tool#26]
Data needs to be updated for fund 8 release.
Two different chunks:

- [x] Proposals data
- [x] Challenges - including briefs
- [x] Criteria
- [x] Example Assessments data

Categories, Criteria and Example assessments can be updated from now, proposals data needs to be updated on March 17th.
I will upload / provide scripts to extract the new data.

**Comment by coire1** [comment]
This is the link of the first part of data for f8 update: https://gist.github.com/coire1/824e65f48d32e9c72ba5ef7e874d4bb3
It includes: 
- [f8-challenges.csv](https://gist.github.com/coire1/824e65f48d32e9c72ba5ef7e874d4bb3#file-f8-challenges-csv) Raw CSV for F8 challenges
- [f7-excellent-assessments.json](https://gist.github.com/coire1/824e65f48d32e9c72ba5ef7e874d4bb3#file-f7-excellent-assessments-json) F7 top 15 excellent assessments
- [f6-excellent-assessments.json](https://gist.github.com/coire1/824e65f48d32e9c72ba5ef7e874d4bb3#file-f6-excellent-assessments-json) F6 top 15 excellent assessments

F7 and F6 excellent assessments should be merged into 1 file. The questions used by `ExampleAssessments.vue` are the same already in the project, no need to update.

**Comment by coire1** [comment]
Here is the draft file for proposals.
Final one will be on Thursday 17th
[proposals.json](https://gist.github.com/coire1/13de4b1e11408bbb0f6f3a1358568609#file-proposals-json)

Related to #34

**Comment by Plamen5kov** [comment]
Done most of the work, need to polush criteria.json and the challenge briefs.

**Comment by coire1** [comment]
This is the final file for proposals: https://gist.github.com/coire1/fcbefaf20c0931c033aaa57f78f79407
